services:
  web:
    build: .
    container_name: pong_web
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=pong_project.settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pong_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: pong_db
    environment:
      POSTGRES_DB: pong_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: pong_redis
    # ports: ["6379:6379"]  # inutile si on n'a pas besoin d'accès hors docker
