services:
  nginx:
    image: nginx:latest
    container_name: pong_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static
      - ./media:/app/media
    depends_on:
      - uvicorn
    networks:
      - pong_network

  uvicorn:
    build: .
    container_name: pong_uvicorn
    command: /app/entrypoint.sh
    volumes:
      - .:/app
      - ./media:/app/media
  
    environment:
      - DJANGO_SETTINGS_MODULE=pong_project.settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pong_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - pong_network

  db:
    image: postgres:15
    container_name: pong_db
    environment:
      POSTGRES_DB: pong_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pong_network

  redis:
    image: redis:alpine
    container_name: pong_redis
    networks:
      - pong_network

networks:
  pong_network:
    driver: bridge

volumes:
  postgres_data:
