# Generated by Django 4.2 on 2025-01-14 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_left', models.CharField(blank=True, max_length=50, null=True)),
                ('player_right', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='running', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='gameresult',
            old_name='played_at',
            new_name='ended_at',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='game.gamesession'),
            preserve_default=False,
        ),
    ]
