# Generated by Django 4.2 on 2025-01-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='looser',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='winner',
            field=models.CharField(max_length=50),
        ),
    ]
