# Generated by Django 4.2 on 2025-01-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(default='waiting', max_length=10),
        ),
    ]
