# Generated by Django 4.2.18 on 2025-01-27 17:59

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='expires_at',
            field=models.DateTimeField(default=game.models.default_expiration_time),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='game.gamesession'),
        ),
        migrations.AlterField(
            model_name='gameinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='GameInvitationParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_speed', models.PositiveSmallIntegerField(choices=[(1, 'Slow'), (2, 'Medium'), (3, 'Fast')], default=2)),
                ('racket_size', models.PositiveSmallIntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=2)),
                ('bonus_malus_activation', models.BooleanField(default=True)),
                ('bumpers_activation', models.BooleanField(default=False)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='game.gameinvitation')),
            ],
        ),
    ]
