# Generated by Django 4.2 on 2025-01-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gameresult_looser_alter_gameresult_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='tournament_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
