# Generated by Django 4.2.18 on 2025-01-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_localtournament_winner_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtournament',
            name='player1',
            field=models.CharField(default='mbappe', max_length=50),
        ),
        migrations.AlterField(
            model_name='localtournament',
            name='player2',
            field=models.CharField(default='zizou', max_length=50),
        ),
        migrations.AlterField(
            model_name='localtournament',
            name='player3',
            field=models.CharField(default='ribery', max_length=50),
        ),
        migrations.AlterField(
            model_name='localtournament',
            name='player4',
            field=models.CharField(default='cantona', max_length=50),
        ),
    ]
