# Generated by Django 4.2 on 2025-01-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtournament',
            name='parameters',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_parameters', to='game.gameparameters'),
        ),
    ]
