version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: pong_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static
    depends_on:
      - uvicorn

  uvicorn:
    build: .
    container_name: pong_uvicorn
    # command: uvicorn pong_project.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=pong_project.settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pong_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: pong_db
    environment:
      POSTGRES_DB: pong_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: pong_redis
